services:
  - type: web
    name: aizenfebp
    runtime: static
    buildCommand: npm install && npm run build  # Corrected to use '&&' for chaining commands
    startCommand: npm run preview
    staticPublishPath: dist
    routes:
      - type: rewrite  # Explicitly specifying the route action (rewrite)
        source: /auth/*
        destination: http://54.206.124.184:5001/*
      - type: rewrite  # Explicitly specifying the route action (rewrite)
        source: /image/*
        destination: http://54.206.124.184:5002/*
      - type: rewrite  # Explicitly specifying the route action (rewrite)
        source: /llm/*
        destination: http://54.206.124.184:5003/*
