services:
  - type: web
    name: aizenfe
    env: node
    plan: free
    buildCommand: npm install && npm run build  # Corrected to use '&&' for chaining commands
    startCommand: npm run preview
    routes:
      - type: rewrite  # Explicitly specifying the route action (rewrite)
        src: /auth/(.*)
        dest: http://54.206.124.184:5001/$1
      - type: rewrite  # Explicitly specifying the route action (rewrite)
        src: /image/(.*)
        dest: http://54.206.124.184:5002/$1
      - type: rewrite  # Explicitly specifying the route action (rewrite)
        src: /llm/(.*)
        dest: http://54.206.124.184:5003/$1
